package edu.hotelManage.entity;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private Short gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.state
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.age
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.face_id
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private String faceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone_number
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.in_date
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private String inDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.salary
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private Integer salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.face_feature
     *
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    private byte[] faceFeature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.state
     *
     * @return the value of employee.state
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.state
     *
     * @param state the value for employee.state
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.age
     *
     * @return the value of employee.age
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.age
     *
     * @param age the value for employee.age
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.face_id
     *
     * @return the value of employee.face_id
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public String getFaceId() {
        return faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.face_id
     *
     * @param faceId the value for employee.face_id
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setFaceId(String faceId) {
        this.faceId = faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone_number
     *
     * @return the value of employee.phone_number
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone_number
     *
     * @param phoneNumber the value for employee.phone_number
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.in_date
     *
     * @return the value of employee.in_date
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public String getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.in_date
     *
     * @param inDate the value for employee.in_date
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setInDate(String inDate) {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            simpleDateFormat.parse(inDate);
        } catch (ParseException e) {
            this.inDate = null;
            e.printStackTrace();
        }
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.salary
     *
     * @return the value of employee.salary
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.salary
     *
     * @param salary the value for employee.salary
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.face_feature
     *
     * @return the value of employee.face_feature
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public byte[] getFaceFeature() {
        return faceFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.face_feature
     *
     * @param faceFeature the value for employee.face_feature
     * @mbg.generated Thu Apr 09 17:53:40 CST 2020
     */
    public void setFaceFeature(byte[] faceFeature) {
        this.faceFeature = faceFeature;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", gender=" + gender +
                ", state='" + state + '\'' +
                ", age=" + age +
                ", faceId='" + faceId + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", inDate=" + inDate +
                ", salary=" + salary +
                ", faceFeature=" + Arrays.toString(faceFeature) +
                '}';
    }
}
