server:
  port: 8020
spring:
  application:
    name: roomManagement
  datasource:
    name: intelhotel
    url: jdbc:mysql://rm-bp161s6e416ikp471co.mysql.rds.aliyuncs.com:3306/hduzq
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: edu.hotelManage.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
