server:
  port: 8050
spring:
  application:
    name: cashManagement
  datasource:
    name: intelhotel
    url: jdbc:mysql://rm-bp161s6e416ikp471co.mysql.rds.aliyuncs.com:3306/hduzq
    username: 
    password: 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: edu.hotelManage.entity
