server:
  port: 8010
spring:
  application:
    name: employeeManagement
  datasource:
    name: intelhotel
    url: jdbc:mysql://localhost:3306/intelhotel?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zq468250
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: edu.hotelManage.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl